name: "Snowflake Terraform Demo Workflow"

on:
  push:
    branches:
      - uat

jobs:
  snowflake-terraform-demo:
    name: "Snowflake Terraform Demo Job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

           
      - name: Terraform Init
        id: init
        run: terraform -chdir=./UAT init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=./UAT validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=./UAT apply -auto-approve
